<a href="https://colab.research.google.com/github/austin-1980/Python-class/blob/main/LoadData(Pandas)(2026199444%EC%8B%A0%ED%98%84%EC%A7%81).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Introduction to Pandas Python</h1>

<p><strong>Welcome!</strong> This notebook will teach you about using <code>Pandas</code> in the Python Programming Language. By the end of this lab, you'll know how to use <code>Pandas</code> package to view and access data.</p>

<h2 id="dataset">About the Dataset</h2>

The table has one row for each album and several columns

<ul>
    <li><b>artist</b>: Name of the artist</li>
    <li><b>album</b>: Name of the album</li>
    <li><b>released_year</b>: Year the album was released</li>
    <li><b>length_min_sec</b>: Length of the album (hours,minutes,seconds)</li>
    <li><b>genre</b>: Genre of the album</li>
    <li><b>music_recording_sales_millions</b>: Music recording sales (millions in USD)</a></li>
    <li><b>claimed_sales_millions</b>: Album's claimed sales (millions in USD) </a></li>
    <li><b>date_released</b>: Date on which the album was released</li>
    <li><b>soundtrack</b>: Indicates if the album is the movie soundtrack (Y) or (N)</li>
    <li><b>rating_of_friends</b>: Indicates the rating from your friends from 1 to 10</li>
</ul>

You can see the dataset here:

<font size="1">
<table font-size:xx-small style="width:25%">
  <tr>
    <th>Artist</th>
    <th>Album</th>
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th>
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td>
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td>
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td>
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td>
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td>
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td>
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td>
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td>
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<hr>

<h2 id="pandas">Introduction of <code>Pandas</code></h2>

In [2]:
# Import required library

import pandas as pd

After the import command, we now have access to a large number of pre-built classes and functions. This assumes the library is installed; in our lab environment all the necessary libraries are installed. One way pandas allows you to work with data is a dataframe. Let's go through the process to go from a comma separated values (<b>.csv</b>) file to a dataframe. This variable <code>csv_path</code> stores the path of the <b>.csv</b>, that is  used as an argument to the <code>read_csv</code> function. The result is stored in the object <code>df</code>, this is a common short form used for a variable referring to a Pandas dataframe.

Creating DataFrame from dict of ndarray/lists: To create DataFrame from dict of narray/list, all the narray must be of same length. If index is passed then the length index should be equal to the length of arrays. If no index is passed, then by default, index will be range(n) where n is the array length.

In [3]:
# Python code demonstrate creating
# DataFrame from dict narray / lists
# By default addresses.

import pandas as pd

# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}

# Create DataFrame
df = pd.DataFrame(data)

# Print the output.
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

#Dataframe

In [4]:
# Read data from CSV file (I will )
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [5]:

csv_path = '/content/gdrive/My Drive/Colab Notebooks/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)

We can use the method <code>head()</code> to examine the first five rows of a dataframe:

 We use the path of the excel file and the function <code>read_excel</code>. The result is a data frame as before:

In [6]:
# Print first five rows of the dataframe
#df.head()

# Print last five rows of the dataframe
df.tail()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

In [26]:
# Read data from Excel File and print the first five rows

xlsx_path = '/content/gdrive/My Drive/Colab Notebooks/TopSellingAlbums.xlsx'

df1 = pd.read_excel(xlsx_path)
df1.head(3)

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0

We can access the column <b>Length</b> and assign it a new dataframe <b>x</b>:

In [29]:
# Access to the column Length

x = df[['Genre']]
x

                         Genre
0               pop, rock, R&B
1                    hard rock
2             progressive rock
3               R&B, soul, pop
4  hard rock, progressive rock
5   rock, soft rock, folk rock
6                        disco
7                    soft rock

 The process is shown in the figure:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Images/DataEgOne.png" width="750" />

<hr>

<h2 id="data">Viewing Data and Accessing Data</h2>

You can also get a column as a series. You can think of a Pandas series as a 1-D dataframe. Just use one bracket:

In [9]:
# Get the column as a series

x = df['Length']
x

0    0:42:19
1    0:42:11
2    0:42:49
3    0:57:44
4    0:46:33
5    0:43:08
6    1:15:54
7    0:40:01
Name: Length, dtype: object

You can also get a column as a dataframe. For example, we can assign the column <b>Artist</b>:

In [10]:
# Get the column as a dataframe

x = df[['Artist']]
x

            Artist
0  Michael Jackson
1            AC/DC
2       Pink Floyd
3  Whitney Houston
4        Meat Loaf
5           Eagles
6         Bee Gees
7    Fleetwood Mac

You can do the same thing for multiple columns; we just put the dataframe name, in this case, <code>df</code>, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns:

In [11]:
# Access to multiple columns

y = df[['Artist','Length','Genre']]
y

            Artist   Length                        Genre
0  Michael Jackson  0:42:19               pop, rock, R&B
1            AC/DC  0:42:11                    hard rock
2       Pink Floyd  0:42:49             progressive rock
3  Whitney Houston  0:57:44               R&B, soul, pop
4        Meat Loaf  0:46:33  hard rock, progressive rock
5           Eagles  0:43:08   rock, soft rock, folk rock
6         Bee Gees  1:15:54                        disco
7    Fleetwood Mac  0:40:01                    soft rock

The process is shown in the figure:

<img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Images/DataEgTwo.png" width="1100" />

One way to access unique elements is the <code>iloc</code> method, where you can access the 1st row and the 1st column as follows:

In [12]:
# Access the value on the first row and the first column

df.iloc[0, 0] #첫번째 행, 첫번째 열

'Michael Jackson'

You can access the 2nd row and the 1st column as follows:

In [13]:
# Access the value on the second row and the first column

df.iloc[1,0] #두번째 행, 첫번째 열

'AC/DC'

You can access the 1st row and the 3rd column as follows:

In [14]:
# Access the value on the first row and the third column

df.iloc[0,2]

np.int64(1982)

You can access the column using the name as well, the following are the same as above:

In [15]:
# Access the column using the name

df.loc[0, 'Artist']

'Michael Jackson'

In [16]:
# Access the column using the name

df.loc[1, 'Artist']

'AC/DC'

In [17]:
# Access the column using the name

df.loc[0, 'Released']

np.int64(1982)

In [18]:
# Access the column using the name

df.loc[1, 'Released']

np.int64(1980)

You can perform slicing using both the index and the name of the column:

In [19]:
# Slicing the dataframe

df.iloc[0:2, 0:3] #row, column sequence

            Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

In [20]:
# Slicing the dataframe using name

df.loc[0:2, 'Artist':'Released'] #iloc, loc의 차이점이 있음...

            Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973

In [21]:
# iterating over rows using iterrows() function
for i, j in df.iterrows():
    print(i, j)
    print()

0 Artist                              Michael Jackson
Album                                      Thriller
Released                                       1982
Length                                      0:42:19
Genre                                pop, rock, R&B
Music Recording Sales (millions)               46.0
Claimed Sales (millions)                         65
Released.1                                30-Nov-82
Soundtrack                                      NaN
Rating                                         10.0
Name: 0, dtype: object

1 Artist                                      AC/DC
Album                               Back in Black
Released                                     1980
Length                                    0:42:11
Genre                                   hard rock
Music Recording Sales (millions)             26.1
Claimed Sales (millions)                       50
Released.1                              25-Jul-80
Soundtrack                                    NaN
Rating                                        9.5
Name: 1, dtype: object

2 Artist                                             Pink Floyd
Album                               The Dark Side of the Moon
Released                                                 1973
Length                                                0:42:49
Genre                                        progressive rock
Music Recording Sales (millions)                         24.2
Claimed Sales (millions)                                   45
Released.1                                          01-Mar-73
Soundtrack                                                NaN
Rating                                                    9.0
Name: 2, dtype: object

3 Artist                              Whitney Houston
Album                                 The Bodyguard
Released                                       1992
Length                                      0:57:44
Genre                                R&B, soul, pop
Music Recording Sales (millions)               27.4
Claimed Sales (millions)                         44
Released.1                                17-Nov-92
Soundtrack                                        Y
Rating                                          8.5
Name: 3, dtype: object

4 Artist                                                Meat Loaf
Album                                           Bat Out of Hell
Released                                                   1977
Length                                                  0:46:33
Genre                               hard rock, progressive rock
Music Recording Sales (millions)                           20.6
Claimed Sales (millions)                                     43
Released.1                                            21-Oct-77
Soundtrack                                                  NaN
Rating                                                      8.0
Name: 4, dtype: object

5 Artist                                                       Eagles
Album                               Their Greatest Hits (1971-1975)
Released                                                       1976
Length                                                      0:43:08
Genre                                    rock, soft rock, folk rock
Music Recording Sales (millions)                               32.2
Claimed Sales (millions)                                         42
Released.1                                                17-Feb-76
Soundtrack                                                      NaN
Rating                                                          7.5
Name: 5, dtype: object

6 Artist                                          Bee Gees
Album                               Saturday Night Fever
Released                                            1977
Length                                           1:15:54
Genre                                              disco
Music Recording Sales (millions)                    20.6
Claimed Sales (millions)                              40
Released.1                                     15-Nov-77
Soundtrack                                             Y
Rating                                               7.0
Name: 6, dtype: object

7 Artist                              Fleetwood Mac
Album                                     Rumours
Released                                     1977
Length                                    0:40:01
Genre                                   soft rock
Music Recording Sales (millions)             27.9
Claimed Sales (millions)                       40
Released.1                              04-Feb-77
Soundtrack                                    NaN
Rating                                        6.5
Name: 7, dtype: object

In [22]:
#Where function --> data science에서 가장 많이 사용하는 기능

# making boolean series for the artist name
filter1 = df["Artist"]=="Michael Jackson"
# making boolean series for Length
filter2 = df["Claimed Sales (millions)"]>45

# filtering data on basis of both filters
df.where(filter2)

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982.0,0:42:19,"pop, rock, R&B",46.0,65.0,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980.0,0:42:11,hard rock,26.1,50.0,25-Jul-80,NaN,9.5
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<hr>

<h2 id="quiz">Quiz on DataFrame</h2>

Use a variable <code>q</code> to store the column <b>Rating</b> as a dataframe

In [35]:
# Write your code below and press Shift+Enter to execute
q= df[['Rating']]
q

   Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5

Double-click __here__ for the solution.

<!-- Your answer is below:
q = df[['Rating']]
q
-->

Assign the variable <code>q</code> to the dataframe that is made up of the column <b>Released</b> and <b>Artist</b>:

In [36]:
# Write your code below and press Shift+Enter to execute
q = df[['Released', 'Artist']]
q

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

Double-click __here__ for the solution.

<!-- Your answer is below:
q = df[['Released', 'Artist']]
q
-->

Access the 2nd row and the 3rd column of <code>df</code>:

In [38]:
# Write your code below and press Shift+Enter to execute
df.iloc[2, 2]

np.int64(1973)

Double-click __here__ for the solution.

<!-- Your answer is below:
df.iloc[1, 2]
-->

<hr>
<h2>The last exercise!</h2>
<p>Congratulations, you have completed your first lesson and hands-on lab in Python. However, there is one more thing you need to do. The Data Science community encourages sharing work. The best way to share and showcase your work is to share it on GitHub. By sharing your notebook on GitHub you are not only building your reputation with fellow data scientists, but you can also show it off when applying for a job. Even though this was your first piece of work, it is never too early to start building good habits. Please submit all your exercises to Github & let the traces in our LMS, so for me to access your work
<hr>

<hr>

<p>Copyright &copy; 2023 RYU HOKYOUNG based on 2018 IBM Developer Skills Network. This notebook and its source code are released under the terms of the<a href="https://cognitiveclass.ai/mit-license/">MIT License</a>.</p>